### ISSUE TITLE
Can you support json-schema?

### ISSUE THREAD

**Issue by wshayes** [ueg1990/faker-schema#1]
For schema definitions?  It looks like the current schema definition is specific to faker-schema.  I generally use JSON-Schema to define data objects as it is getting to be fairly expressive and more widely used.

**Comment by ueg1990** [comment]
Hello, someone asked me this before too. I am trying to understand how we can support json-schema for this project. w.r.t. json-schema, the types would be built-in types like int, float, array, string, boolean etc. And without knowing context of each key, all we can do is randomly generate values based on the type in schema (defined by json-schema).

For example, if we have {"properties": {"name": {"type": "string"}}} as a schema, the best we will be able to do it faker.random_string (or whatever is the correct method call for this type). While if we use the types defined in the faker library (which are called Providers), we can have a schema {"name": "name"} and faker will return real-world values. Also you can have more variety and options by using other different types provided related to name like first_name, first_name_female etc. (http://faker.readthedocs.io/en/master/providers/faker.providers.person.html)

If you have an example or use case where we can incorporate json-schema, please share :)

**Comment by wshayes** [comment]
It looks like the format keyword in JSON-Schema could be used for defining specific faker types/providers.  See Format section here:  https://spacetelescope.github.io/understanding-json-schema/reference/string.html

I agree with you - the basic types won't be terribly helpful for Faker-schema

Nice module BTW!

**Comment by ueg1990** [comment]
thank you :)
